import "./globals.css";


import MyApp from "./_app";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-200">
        {children}
      </body>
    </html >
  );
}
